"""Criação inicial das tabelas usuario, entrega e localizacao

Revision ID: a4170c637eaf
Revises: 
Create Date: 2025-09-30 23:35:11.201382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4170c637eaf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuario',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('placa_veiculo', sa.String(length=8), nullable=False),
    sa.Column('cnh', sa.String(length=11), nullable=False),
    sa.Column('telefone', sa.String(length=11), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('entrega',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('motorista_id', sa.UUID(), nullable=False),
    sa.Column('endereco_entrega', sa.String(length=255), nullable=False),
    sa.Column('numero_pedido', sa.String(length=6), nullable=False),
    sa.Column('status', sa.Enum('PENDENTE', 'EM_ROTA', 'ENTREGUE', 'CANCELADA', 'NAO_ENTREGUE', name='statusentrega'), nullable=True),
    sa.Column('nome_cliente', sa.String(length=255), nullable=False),
    sa.Column('nome_recebido', sa.String(length=255), nullable=True),
    sa.Column('descricao', sa.String(length=255), nullable=True),
    sa.Column('observacao', sa.String(length=255), nullable=True),
    sa.Column('foto_prova', sa.String(length=255), nullable=True),
    sa.Column('motivo', sa.String(length=255), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['motorista_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_pedido')
    )
    op.create_table('localizacao',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entrega_id', sa.UUID(), nullable=True),
    sa.Column('motorista_id', sa.UUID(), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=10, scale=7), nullable=False),
    sa.Column('longitude', sa.Numeric(precision=10, scale=7), nullable=False),
    sa.Column('data_hora', sa.DateTime(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['entrega_id'], ['entrega.id'], ),
    sa.ForeignKeyConstraint(['motorista_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('localizacao')
    op.drop_table('entrega')
    op.drop_table('usuario')
    # ### end Alembic commands ###
