"""Ajusta tamanho da coluna placa_veiculo para 8

Revision ID: a91895f248b6
Revises: a4170c637eaf
Create Date: 2025-10-09 00:03:21.665486

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a91895f248b6'
down_revision = 'a4170c637eaf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sensor')
    with op.batch_alter_table('entrega', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=postgresql.ENUM('PENDENTE', 'EM_ROTA', 'ENTREGUE', 'CANCELADA', 'NAO_ENTREGUE', name='statusentrega'),
               nullable=False)
        batch_op.drop_column('descricao')

    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.alter_column('placa_veiculo',
               existing_type=sa.VARCHAR(length=7),
               type_=sa.String(length=8),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.alter_column('placa_veiculo',
               existing_type=sa.String(length=8),
               type_=sa.VARCHAR(length=7),
               existing_nullable=False)

    with op.batch_alter_table('entrega', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descricao', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.alter_column('status',
               existing_type=postgresql.ENUM('PENDENTE', 'EM_ROTA', 'ENTREGUE', 'CANCELADA', 'NAO_ENTREGUE', name='statusentrega'),
               nullable=True)

    op.create_table('sensor',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tipo', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('dados', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('data', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('sensor_pkey'))
    )
    # ### end Alembic commands ###
